/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.enums;


import com.example.demo.jooqmodels.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum OrderStatus implements EnumType {

    PENDING_PAYMENT("PENDING_PAYMENT"),

    PAID("PAID"),

    CANCELLED("CANCELLED");

    private final String literal;

    private OrderStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "order_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static OrderStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(OrderStatus.class, literal);
    }
}
