/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels;


import com.example.demo.jooqmodels.tables.Admins;
import com.example.demo.jooqmodels.tables.CustomerCartConfigurableItems;
import com.example.demo.jooqmodels.tables.CustomerCartSimpleItems;
import com.example.demo.jooqmodels.tables.Customers;
import com.example.demo.jooqmodels.tables.KnexMigrations;
import com.example.demo.jooqmodels.tables.KnexMigrationsLock;
import com.example.demo.jooqmodels.tables.OrderLineConfigurableItems;
import com.example.demo.jooqmodels.tables.OrderLineSimpleItems;
import com.example.demo.jooqmodels.tables.Orders;
import com.example.demo.jooqmodels.tables.ProductAssociationTypes;
import com.example.demo.jooqmodels.tables.ProductAssociations;
import com.example.demo.jooqmodels.tables.ProductConfigurableOptions;
import com.example.demo.jooqmodels.tables.ProductOptionValues;
import com.example.demo.jooqmodels.tables.ProductOptions;
import com.example.demo.jooqmodels.tables.ProductReviews;
import com.example.demo.jooqmodels.tables.ProductTaxons;
import com.example.demo.jooqmodels.tables.ProductVariantOptions;
import com.example.demo.jooqmodels.tables.ProductVariants;
import com.example.demo.jooqmodels.tables.Products;
import com.example.demo.jooqmodels.tables.Taxons;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.admins</code>.
     */
    public final Admins ADMINS = Admins.ADMINS;

    /**
     * The table <code>public.customer_cart_configurable_items</code>.
     */
    public final CustomerCartConfigurableItems CUSTOMER_CART_CONFIGURABLE_ITEMS = CustomerCartConfigurableItems.CUSTOMER_CART_CONFIGURABLE_ITEMS;

    /**
     * The table <code>public.customer_cart_simple_items</code>.
     */
    public final CustomerCartSimpleItems CUSTOMER_CART_SIMPLE_ITEMS = CustomerCartSimpleItems.CUSTOMER_CART_SIMPLE_ITEMS;

    /**
     * The table <code>public.customers</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.knex_migrations</code>.
     */
    public final KnexMigrations KNEX_MIGRATIONS = KnexMigrations.KNEX_MIGRATIONS;

    /**
     * The table <code>public.knex_migrations_lock</code>.
     */
    public final KnexMigrationsLock KNEX_MIGRATIONS_LOCK = KnexMigrationsLock.KNEX_MIGRATIONS_LOCK;

    /**
     * The table <code>public.order_line_configurable_items</code>.
     */
    public final OrderLineConfigurableItems ORDER_LINE_CONFIGURABLE_ITEMS = OrderLineConfigurableItems.ORDER_LINE_CONFIGURABLE_ITEMS;

    /**
     * The table <code>public.order_line_simple_items</code>.
     */
    public final OrderLineSimpleItems ORDER_LINE_SIMPLE_ITEMS = OrderLineSimpleItems.ORDER_LINE_SIMPLE_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.product_association_types</code>.
     */
    public final ProductAssociationTypes PRODUCT_ASSOCIATION_TYPES = ProductAssociationTypes.PRODUCT_ASSOCIATION_TYPES;

    /**
     * The table <code>public.product_associations</code>.
     */
    public final ProductAssociations PRODUCT_ASSOCIATIONS = ProductAssociations.PRODUCT_ASSOCIATIONS;

    /**
     * The table <code>public.product_configurable_options</code>.
     */
    public final ProductConfigurableOptions PRODUCT_CONFIGURABLE_OPTIONS = ProductConfigurableOptions.PRODUCT_CONFIGURABLE_OPTIONS;

    /**
     * The table <code>public.product_option_values</code>.
     */
    public final ProductOptionValues PRODUCT_OPTION_VALUES = ProductOptionValues.PRODUCT_OPTION_VALUES;

    /**
     * The table <code>public.product_options</code>.
     */
    public final ProductOptions PRODUCT_OPTIONS = ProductOptions.PRODUCT_OPTIONS;

    /**
     * The table <code>public.product_reviews</code>.
     */
    public final ProductReviews PRODUCT_REVIEWS = ProductReviews.PRODUCT_REVIEWS;

    /**
     * The table <code>public.product_taxons</code>.
     */
    public final ProductTaxons PRODUCT_TAXONS = ProductTaxons.PRODUCT_TAXONS;

    /**
     * The table <code>public.product_variant_options</code>.
     */
    public final ProductVariantOptions PRODUCT_VARIANT_OPTIONS = ProductVariantOptions.PRODUCT_VARIANT_OPTIONS;

    /**
     * The table <code>public.product_variants</code>.
     */
    public final ProductVariants PRODUCT_VARIANTS = ProductVariants.PRODUCT_VARIANTS;

    /**
     * The table <code>public.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.taxons</code>.
     */
    public final Taxons TAXONS = Taxons.TAXONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Admins.ADMINS,
            CustomerCartConfigurableItems.CUSTOMER_CART_CONFIGURABLE_ITEMS,
            CustomerCartSimpleItems.CUSTOMER_CART_SIMPLE_ITEMS,
            Customers.CUSTOMERS,
            KnexMigrations.KNEX_MIGRATIONS,
            KnexMigrationsLock.KNEX_MIGRATIONS_LOCK,
            OrderLineConfigurableItems.ORDER_LINE_CONFIGURABLE_ITEMS,
            OrderLineSimpleItems.ORDER_LINE_SIMPLE_ITEMS,
            Orders.ORDERS,
            ProductAssociationTypes.PRODUCT_ASSOCIATION_TYPES,
            ProductAssociations.PRODUCT_ASSOCIATIONS,
            ProductConfigurableOptions.PRODUCT_CONFIGURABLE_OPTIONS,
            ProductOptionValues.PRODUCT_OPTION_VALUES,
            ProductOptions.PRODUCT_OPTIONS,
            ProductReviews.PRODUCT_REVIEWS,
            ProductTaxons.PRODUCT_TAXONS,
            ProductVariantOptions.PRODUCT_VARIANT_OPTIONS,
            ProductVariants.PRODUCT_VARIANTS,
            Products.PRODUCTS,
            Taxons.TAXONS
        );
    }
}
