/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels;


import com.example.demo.jooqmodels.tables.Admins;
import com.example.demo.jooqmodels.tables.CustomerCartConfigurableItems;
import com.example.demo.jooqmodels.tables.CustomerCartSimpleItems;
import com.example.demo.jooqmodels.tables.Customers;
import com.example.demo.jooqmodels.tables.KnexMigrations;
import com.example.demo.jooqmodels.tables.KnexMigrationsLock;
import com.example.demo.jooqmodels.tables.OrderLineConfigurableItems;
import com.example.demo.jooqmodels.tables.OrderLineSimpleItems;
import com.example.demo.jooqmodels.tables.Orders;
import com.example.demo.jooqmodels.tables.ProductAssociationTypes;
import com.example.demo.jooqmodels.tables.ProductAssociations;
import com.example.demo.jooqmodels.tables.ProductConfigurableOptions;
import com.example.demo.jooqmodels.tables.ProductOptionValues;
import com.example.demo.jooqmodels.tables.ProductOptions;
import com.example.demo.jooqmodels.tables.ProductReviews;
import com.example.demo.jooqmodels.tables.ProductTaxons;
import com.example.demo.jooqmodels.tables.ProductVariantOptions;
import com.example.demo.jooqmodels.tables.ProductVariants;
import com.example.demo.jooqmodels.tables.Products;
import com.example.demo.jooqmodels.tables.Taxons;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.admins</code>.
     */
    public static final Admins ADMINS = Admins.ADMINS;

    /**
     * The table <code>public.customer_cart_configurable_items</code>.
     */
    public static final CustomerCartConfigurableItems CUSTOMER_CART_CONFIGURABLE_ITEMS = CustomerCartConfigurableItems.CUSTOMER_CART_CONFIGURABLE_ITEMS;

    /**
     * The table <code>public.customer_cart_simple_items</code>.
     */
    public static final CustomerCartSimpleItems CUSTOMER_CART_SIMPLE_ITEMS = CustomerCartSimpleItems.CUSTOMER_CART_SIMPLE_ITEMS;

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.knex_migrations</code>.
     */
    public static final KnexMigrations KNEX_MIGRATIONS = KnexMigrations.KNEX_MIGRATIONS;

    /**
     * The table <code>public.knex_migrations_lock</code>.
     */
    public static final KnexMigrationsLock KNEX_MIGRATIONS_LOCK = KnexMigrationsLock.KNEX_MIGRATIONS_LOCK;

    /**
     * The table <code>public.order_line_configurable_items</code>.
     */
    public static final OrderLineConfigurableItems ORDER_LINE_CONFIGURABLE_ITEMS = OrderLineConfigurableItems.ORDER_LINE_CONFIGURABLE_ITEMS;

    /**
     * The table <code>public.order_line_simple_items</code>.
     */
    public static final OrderLineSimpleItems ORDER_LINE_SIMPLE_ITEMS = OrderLineSimpleItems.ORDER_LINE_SIMPLE_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.product_association_types</code>.
     */
    public static final ProductAssociationTypes PRODUCT_ASSOCIATION_TYPES = ProductAssociationTypes.PRODUCT_ASSOCIATION_TYPES;

    /**
     * The table <code>public.product_associations</code>.
     */
    public static final ProductAssociations PRODUCT_ASSOCIATIONS = ProductAssociations.PRODUCT_ASSOCIATIONS;

    /**
     * The table <code>public.product_configurable_options</code>.
     */
    public static final ProductConfigurableOptions PRODUCT_CONFIGURABLE_OPTIONS = ProductConfigurableOptions.PRODUCT_CONFIGURABLE_OPTIONS;

    /**
     * The table <code>public.product_option_values</code>.
     */
    public static final ProductOptionValues PRODUCT_OPTION_VALUES = ProductOptionValues.PRODUCT_OPTION_VALUES;

    /**
     * The table <code>public.product_options</code>.
     */
    public static final ProductOptions PRODUCT_OPTIONS = ProductOptions.PRODUCT_OPTIONS;

    /**
     * The table <code>public.product_reviews</code>.
     */
    public static final ProductReviews PRODUCT_REVIEWS = ProductReviews.PRODUCT_REVIEWS;

    /**
     * The table <code>public.product_taxons</code>.
     */
    public static final ProductTaxons PRODUCT_TAXONS = ProductTaxons.PRODUCT_TAXONS;

    /**
     * The table <code>public.product_variant_options</code>.
     */
    public static final ProductVariantOptions PRODUCT_VARIANT_OPTIONS = ProductVariantOptions.PRODUCT_VARIANT_OPTIONS;

    /**
     * The table <code>public.product_variants</code>.
     */
    public static final ProductVariants PRODUCT_VARIANTS = ProductVariants.PRODUCT_VARIANTS;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.taxons</code>.
     */
    public static final Taxons TAXONS = Taxons.TAXONS;
}
