package com.example.demo.services.common.exceptions;

public enum ErrorCode {
  RESOURCE_NOT_FOUND,
  AUTH_UNAUTHORIZED,
  AUTH_INCORRECT_PASSWORD,
  DB_DELETED_ENTITY_IN_USE,
  DB_UNIQUE_VALUE_CONFLICT,
  PRODUCT_OPTION_MULTIPLE_OPTION_VALUES_WITH_SAME_NAME,
  PRODUCT_VARIANT_CONFLICT_OPTION_VALUES,
  PRODUCT_VARIANT_MULTI_CONFLICT_OPTION_VALUES,
  PRODUCT_VARIANT_CONFLICT_VARIANT_NAMES,
}
