/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables;


import com.example.demo.jooqmodels.Keys;
import com.example.demo.jooqmodels.Public;
import com.example.demo.jooqmodels.tables.Customers.CustomersPath;
import com.example.demo.jooqmodels.tables.Products.ProductsPath;
import com.example.demo.jooqmodels.tables.records.CustomerCartSimpleItemsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerCartSimpleItems extends TableImpl<CustomerCartSimpleItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.customer_cart_simple_items</code>
     */
    public static final CustomerCartSimpleItems CUSTOMER_CART_SIMPLE_ITEMS = new CustomerCartSimpleItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerCartSimpleItemsRecord> getRecordType() {
        return CustomerCartSimpleItemsRecord.class;
    }

    /**
     * The column <code>public.customer_cart_simple_items.customer_id</code>.
     */
    public final TableField<CustomerCartSimpleItemsRecord, Integer> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.customer_cart_simple_items.product_id</code>.
     */
    public final TableField<CustomerCartSimpleItemsRecord, Integer> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.customer_cart_simple_items.quantity</code>.
     */
    public final TableField<CustomerCartSimpleItemsRecord, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.customer_cart_simple_items.added_at</code>.
     */
    public final TableField<CustomerCartSimpleItemsRecord, LocalDateTime> ADDED_AT = createField(DSL.name("added_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private CustomerCartSimpleItems(Name alias, Table<CustomerCartSimpleItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerCartSimpleItems(Name alias, Table<CustomerCartSimpleItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.customer_cart_simple_items</code> table
     * reference
     */
    public CustomerCartSimpleItems(String alias) {
        this(DSL.name(alias), CUSTOMER_CART_SIMPLE_ITEMS);
    }

    /**
     * Create an aliased <code>public.customer_cart_simple_items</code> table
     * reference
     */
    public CustomerCartSimpleItems(Name alias) {
        this(alias, CUSTOMER_CART_SIMPLE_ITEMS);
    }

    /**
     * Create a <code>public.customer_cart_simple_items</code> table reference
     */
    public CustomerCartSimpleItems() {
        this(DSL.name("customer_cart_simple_items"), null);
    }

    public <O extends Record> CustomerCartSimpleItems(Table<O> path, ForeignKey<O, CustomerCartSimpleItemsRecord> childPath, InverseForeignKey<O, CustomerCartSimpleItemsRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOMER_CART_SIMPLE_ITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CustomerCartSimpleItemsPath extends CustomerCartSimpleItems implements Path<CustomerCartSimpleItemsRecord> {
        public <O extends Record> CustomerCartSimpleItemsPath(Table<O> path, ForeignKey<O, CustomerCartSimpleItemsRecord> childPath, InverseForeignKey<O, CustomerCartSimpleItemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomerCartSimpleItemsPath(Name alias, Table<CustomerCartSimpleItemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomerCartSimpleItemsPath as(String alias) {
            return new CustomerCartSimpleItemsPath(DSL.name(alias), this);
        }

        @Override
        public CustomerCartSimpleItemsPath as(Name alias) {
            return new CustomerCartSimpleItemsPath(alias, this);
        }

        @Override
        public CustomerCartSimpleItemsPath as(Table<?> alias) {
            return new CustomerCartSimpleItemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CustomerCartSimpleItemsRecord> getPrimaryKey() {
        return Keys.CUSTOMER_CART_SIMPLE_ITEMS_PKEY;
    }

    @Override
    public List<ForeignKey<CustomerCartSimpleItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CUSTOMER_CART_SIMPLE_ITEMS__CUSTOMER_CART_SIMPLE_ITEMS_CUSTOMER_ID_FKEY, Keys.CUSTOMER_CART_SIMPLE_ITEMS__CUSTOMER_CART_SIMPLE_ITEMS_PRODUCT_ID_FKEY);
    }

    private transient CustomersPath _customers;

    /**
     * Get the implicit join path to the <code>public.customers</code> table.
     */
    public CustomersPath customers() {
        if (_customers == null)
            _customers = new CustomersPath(this, Keys.CUSTOMER_CART_SIMPLE_ITEMS__CUSTOMER_CART_SIMPLE_ITEMS_CUSTOMER_ID_FKEY, null);

        return _customers;
    }

    private transient ProductsPath _products;

    /**
     * Get the implicit join path to the <code>public.products</code> table.
     */
    public ProductsPath products() {
        if (_products == null)
            _products = new ProductsPath(this, Keys.CUSTOMER_CART_SIMPLE_ITEMS__CUSTOMER_CART_SIMPLE_ITEMS_PRODUCT_ID_FKEY, null);

        return _products;
    }

    @Override
    public CustomerCartSimpleItems as(String alias) {
        return new CustomerCartSimpleItems(DSL.name(alias), this);
    }

    @Override
    public CustomerCartSimpleItems as(Name alias) {
        return new CustomerCartSimpleItems(alias, this);
    }

    @Override
    public CustomerCartSimpleItems as(Table<?> alias) {
        return new CustomerCartSimpleItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCartSimpleItems rename(String name) {
        return new CustomerCartSimpleItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCartSimpleItems rename(Name name) {
        return new CustomerCartSimpleItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerCartSimpleItems rename(Table<?> name) {
        return new CustomerCartSimpleItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCartSimpleItems where(Condition condition) {
        return new CustomerCartSimpleItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCartSimpleItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCartSimpleItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCartSimpleItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCartSimpleItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCartSimpleItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCartSimpleItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerCartSimpleItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCartSimpleItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerCartSimpleItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
