/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables;


import com.example.demo.jooqmodels.Keys;
import com.example.demo.jooqmodels.Public;
import com.example.demo.jooqmodels.tables.records.KnexMigrationsLockRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KnexMigrationsLock extends TableImpl<KnexMigrationsLockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.knex_migrations_lock</code>
     */
    public static final KnexMigrationsLock KNEX_MIGRATIONS_LOCK = new KnexMigrationsLock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KnexMigrationsLockRecord> getRecordType() {
        return KnexMigrationsLockRecord.class;
    }

    /**
     * The column <code>public.knex_migrations_lock.index</code>.
     */
    public final TableField<KnexMigrationsLockRecord, Integer> INDEX = createField(DSL.name("index"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.knex_migrations_lock.is_locked</code>.
     */
    public final TableField<KnexMigrationsLockRecord, Integer> IS_LOCKED = createField(DSL.name("is_locked"), SQLDataType.INTEGER, this, "");

    private KnexMigrationsLock(Name alias, Table<KnexMigrationsLockRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private KnexMigrationsLock(Name alias, Table<KnexMigrationsLockRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.knex_migrations_lock</code> table
     * reference
     */
    public KnexMigrationsLock(String alias) {
        this(DSL.name(alias), KNEX_MIGRATIONS_LOCK);
    }

    /**
     * Create an aliased <code>public.knex_migrations_lock</code> table
     * reference
     */
    public KnexMigrationsLock(Name alias) {
        this(alias, KNEX_MIGRATIONS_LOCK);
    }

    /**
     * Create a <code>public.knex_migrations_lock</code> table reference
     */
    public KnexMigrationsLock() {
        this(DSL.name("knex_migrations_lock"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<KnexMigrationsLockRecord, Integer> getIdentity() {
        return (Identity<KnexMigrationsLockRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<KnexMigrationsLockRecord> getPrimaryKey() {
        return Keys.KNEX_MIGRATIONS_LOCK_PKEY;
    }

    @Override
    public KnexMigrationsLock as(String alias) {
        return new KnexMigrationsLock(DSL.name(alias), this);
    }

    @Override
    public KnexMigrationsLock as(Name alias) {
        return new KnexMigrationsLock(alias, this);
    }

    @Override
    public KnexMigrationsLock as(Table<?> alias) {
        return new KnexMigrationsLock(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public KnexMigrationsLock rename(String name) {
        return new KnexMigrationsLock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KnexMigrationsLock rename(Name name) {
        return new KnexMigrationsLock(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public KnexMigrationsLock rename(Table<?> name) {
        return new KnexMigrationsLock(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KnexMigrationsLock where(Condition condition) {
        return new KnexMigrationsLock(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KnexMigrationsLock where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KnexMigrationsLock where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KnexMigrationsLock where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KnexMigrationsLock where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KnexMigrationsLock where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KnexMigrationsLock where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KnexMigrationsLock where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KnexMigrationsLock whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KnexMigrationsLock whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
