/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables;


import com.example.demo.jooqmodels.Keys;
import com.example.demo.jooqmodels.Public;
import com.example.demo.jooqmodels.tables.ProductOptions.ProductOptionsPath;
import com.example.demo.jooqmodels.tables.ProductVariantOptions.ProductVariantOptionsPath;
import com.example.demo.jooqmodels.tables.ProductVariants.ProductVariantsPath;
import com.example.demo.jooqmodels.tables.records.ProductOptionValuesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductOptionValues extends TableImpl<ProductOptionValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.product_option_values</code>
     */
    public static final ProductOptionValues PRODUCT_OPTION_VALUES = new ProductOptionValues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductOptionValuesRecord> getRecordType() {
        return ProductOptionValuesRecord.class;
    }

    /**
     * The column <code>public.product_option_values.id</code>.
     */
    public final TableField<ProductOptionValuesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.product_option_values.option_code</code>.
     */
    public final TableField<ProductOptionValuesRecord, String> OPTION_CODE = createField(DSL.name("option_code"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.product_option_values.option_value</code>.
     */
    public final TableField<ProductOptionValuesRecord, String> OPTION_VALUE = createField(DSL.name("option_value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.product_option_values.updated_at</code>.
     */
    public final TableField<ProductOptionValuesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.product_option_values.created_at</code>.
     */
    public final TableField<ProductOptionValuesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ProductOptionValues(Name alias, Table<ProductOptionValuesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProductOptionValues(Name alias, Table<ProductOptionValuesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.product_option_values</code> table
     * reference
     */
    public ProductOptionValues(String alias) {
        this(DSL.name(alias), PRODUCT_OPTION_VALUES);
    }

    /**
     * Create an aliased <code>public.product_option_values</code> table
     * reference
     */
    public ProductOptionValues(Name alias) {
        this(alias, PRODUCT_OPTION_VALUES);
    }

    /**
     * Create a <code>public.product_option_values</code> table reference
     */
    public ProductOptionValues() {
        this(DSL.name("product_option_values"), null);
    }

    public <O extends Record> ProductOptionValues(Table<O> path, ForeignKey<O, ProductOptionValuesRecord> childPath, InverseForeignKey<O, ProductOptionValuesRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCT_OPTION_VALUES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductOptionValuesPath extends ProductOptionValues implements Path<ProductOptionValuesRecord> {
        public <O extends Record> ProductOptionValuesPath(Table<O> path, ForeignKey<O, ProductOptionValuesRecord> childPath, InverseForeignKey<O, ProductOptionValuesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductOptionValuesPath(Name alias, Table<ProductOptionValuesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductOptionValuesPath as(String alias) {
            return new ProductOptionValuesPath(DSL.name(alias), this);
        }

        @Override
        public ProductOptionValuesPath as(Name alias) {
            return new ProductOptionValuesPath(alias, this);
        }

        @Override
        public ProductOptionValuesPath as(Table<?> alias) {
            return new ProductOptionValuesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ProductOptionValuesRecord, Integer> getIdentity() {
        return (Identity<ProductOptionValuesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductOptionValuesRecord> getPrimaryKey() {
        return Keys.PRODUCT_OPTION_VALUES_PKEY;
    }

    @Override
    public List<UniqueKey<ProductOptionValuesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PRODUCT_OPTION_VALUES_OPTION_CODE_OPTION_VALUE_KEY);
    }

    @Override
    public List<ForeignKey<ProductOptionValuesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_OPTION_VALUES__PRODUCT_OPTION_VALUES_OPTION_CODE_FKEY);
    }

    private transient ProductOptionsPath _productOptions;

    /**
     * Get the implicit join path to the <code>public.product_options</code>
     * table.
     */
    public ProductOptionsPath productOptions() {
        if (_productOptions == null)
            _productOptions = new ProductOptionsPath(this, Keys.PRODUCT_OPTION_VALUES__PRODUCT_OPTION_VALUES_OPTION_CODE_FKEY, null);

        return _productOptions;
    }

    private transient ProductVariantOptionsPath _productVariantOptions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.product_variant_options</code> table
     */
    public ProductVariantOptionsPath productVariantOptions() {
        if (_productVariantOptions == null)
            _productVariantOptions = new ProductVariantOptionsPath(this, null, Keys.PRODUCT_VARIANT_OPTIONS__PRODUCT_VARIANT_OPTIONS_PRODUCT_OPTION_VALUE_ID_FKEY.getInverseKey());

        return _productVariantOptions;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.product_variants</code> table
     */
    public ProductVariantsPath productVariants() {
        return productVariantOptions().productVariants();
    }

    @Override
    public ProductOptionValues as(String alias) {
        return new ProductOptionValues(DSL.name(alias), this);
    }

    @Override
    public ProductOptionValues as(Name alias) {
        return new ProductOptionValues(alias, this);
    }

    @Override
    public ProductOptionValues as(Table<?> alias) {
        return new ProductOptionValues(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductOptionValues rename(String name) {
        return new ProductOptionValues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductOptionValues rename(Name name) {
        return new ProductOptionValues(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductOptionValues rename(Table<?> name) {
        return new ProductOptionValues(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOptionValues where(Condition condition) {
        return new ProductOptionValues(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOptionValues where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOptionValues where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOptionValues where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOptionValues where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOptionValues where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOptionValues where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductOptionValues where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOptionValues whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductOptionValues whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
