/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables;


import com.example.demo.jooqmodels.Keys;
import com.example.demo.jooqmodels.Public;
import com.example.demo.jooqmodels.tables.Orders.OrdersPath;
import com.example.demo.jooqmodels.tables.Products.ProductsPath;
import com.example.demo.jooqmodels.tables.records.ProductReviewsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductReviews extends TableImpl<ProductReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.product_reviews</code>
     */
    public static final ProductReviews PRODUCT_REVIEWS = new ProductReviews();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductReviewsRecord> getRecordType() {
        return ProductReviewsRecord.class;
    }

    /**
     * The column <code>public.product_reviews.order_id</code>.
     */
    public final TableField<ProductReviewsRecord, Integer> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.product_reviews.product_id</code>.
     */
    public final TableField<ProductReviewsRecord, Integer> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.product_reviews.comment</code>.
     */
    public final TableField<ProductReviewsRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.product_reviews.rating</code>.
     */
    public final TableField<ProductReviewsRecord, Integer> RATING = createField(DSL.name("rating"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.product_reviews.created_at</code>.
     */
    public final TableField<ProductReviewsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ProductReviews(Name alias, Table<ProductReviewsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProductReviews(Name alias, Table<ProductReviewsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.product_reviews</code> table reference
     */
    public ProductReviews(String alias) {
        this(DSL.name(alias), PRODUCT_REVIEWS);
    }

    /**
     * Create an aliased <code>public.product_reviews</code> table reference
     */
    public ProductReviews(Name alias) {
        this(alias, PRODUCT_REVIEWS);
    }

    /**
     * Create a <code>public.product_reviews</code> table reference
     */
    public ProductReviews() {
        this(DSL.name("product_reviews"), null);
    }

    public <O extends Record> ProductReviews(Table<O> path, ForeignKey<O, ProductReviewsRecord> childPath, InverseForeignKey<O, ProductReviewsRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCT_REVIEWS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductReviewsPath extends ProductReviews implements Path<ProductReviewsRecord> {
        public <O extends Record> ProductReviewsPath(Table<O> path, ForeignKey<O, ProductReviewsRecord> childPath, InverseForeignKey<O, ProductReviewsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductReviewsPath(Name alias, Table<ProductReviewsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductReviewsPath as(String alias) {
            return new ProductReviewsPath(DSL.name(alias), this);
        }

        @Override
        public ProductReviewsPath as(Name alias) {
            return new ProductReviewsPath(alias, this);
        }

        @Override
        public ProductReviewsPath as(Table<?> alias) {
            return new ProductReviewsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ProductReviewsRecord> getPrimaryKey() {
        return Keys.PRODUCT_REVIEWS_PKEY;
    }

    @Override
    public List<ForeignKey<ProductReviewsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_REVIEWS__PRODUCT_REVIEWS_ORDER_ID_FKEY, Keys.PRODUCT_REVIEWS__PRODUCT_REVIEWS_PRODUCT_ID_FKEY);
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit join path to the <code>public.orders</code> table.
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, Keys.PRODUCT_REVIEWS__PRODUCT_REVIEWS_ORDER_ID_FKEY, null);

        return _orders;
    }

    private transient ProductsPath _products;

    /**
     * Get the implicit join path to the <code>public.products</code> table.
     */
    public ProductsPath products() {
        if (_products == null)
            _products = new ProductsPath(this, Keys.PRODUCT_REVIEWS__PRODUCT_REVIEWS_PRODUCT_ID_FKEY, null);

        return _products;
    }

    @Override
    public ProductReviews as(String alias) {
        return new ProductReviews(DSL.name(alias), this);
    }

    @Override
    public ProductReviews as(Name alias) {
        return new ProductReviews(alias, this);
    }

    @Override
    public ProductReviews as(Table<?> alias) {
        return new ProductReviews(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductReviews rename(String name) {
        return new ProductReviews(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductReviews rename(Name name) {
        return new ProductReviews(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductReviews rename(Table<?> name) {
        return new ProductReviews(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Condition condition) {
        return new ProductReviews(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductReviews where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductReviews whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
