/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables;


import com.example.demo.jooqmodels.Keys;
import com.example.demo.jooqmodels.Public;
import com.example.demo.jooqmodels.tables.ProductOptionValues.ProductOptionValuesPath;
import com.example.demo.jooqmodels.tables.ProductVariants.ProductVariantsPath;
import com.example.demo.jooqmodels.tables.records.ProductVariantOptionsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductVariantOptions extends TableImpl<ProductVariantOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.product_variant_options</code>
     */
    public static final ProductVariantOptions PRODUCT_VARIANT_OPTIONS = new ProductVariantOptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductVariantOptionsRecord> getRecordType() {
        return ProductVariantOptionsRecord.class;
    }

    /**
     * The column <code>public.product_variant_options.id</code>.
     */
    public final TableField<ProductVariantOptionsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.product_variant_options.product_variant_id</code>.
     */
    public final TableField<ProductVariantOptionsRecord, Integer> PRODUCT_VARIANT_ID = createField(DSL.name("product_variant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.product_variant_options.product_option_value_id</code>.
     */
    public final TableField<ProductVariantOptionsRecord, Integer> PRODUCT_OPTION_VALUE_ID = createField(DSL.name("product_option_value_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.product_variant_options.updated_at</code>.
     */
    public final TableField<ProductVariantOptionsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.product_variant_options.created_at</code>.
     */
    public final TableField<ProductVariantOptionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ProductVariantOptions(Name alias, Table<ProductVariantOptionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProductVariantOptions(Name alias, Table<ProductVariantOptionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.product_variant_options</code> table
     * reference
     */
    public ProductVariantOptions(String alias) {
        this(DSL.name(alias), PRODUCT_VARIANT_OPTIONS);
    }

    /**
     * Create an aliased <code>public.product_variant_options</code> table
     * reference
     */
    public ProductVariantOptions(Name alias) {
        this(alias, PRODUCT_VARIANT_OPTIONS);
    }

    /**
     * Create a <code>public.product_variant_options</code> table reference
     */
    public ProductVariantOptions() {
        this(DSL.name("product_variant_options"), null);
    }

    public <O extends Record> ProductVariantOptions(Table<O> path, ForeignKey<O, ProductVariantOptionsRecord> childPath, InverseForeignKey<O, ProductVariantOptionsRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCT_VARIANT_OPTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductVariantOptionsPath extends ProductVariantOptions implements Path<ProductVariantOptionsRecord> {
        public <O extends Record> ProductVariantOptionsPath(Table<O> path, ForeignKey<O, ProductVariantOptionsRecord> childPath, InverseForeignKey<O, ProductVariantOptionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductVariantOptionsPath(Name alias, Table<ProductVariantOptionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductVariantOptionsPath as(String alias) {
            return new ProductVariantOptionsPath(DSL.name(alias), this);
        }

        @Override
        public ProductVariantOptionsPath as(Name alias) {
            return new ProductVariantOptionsPath(alias, this);
        }

        @Override
        public ProductVariantOptionsPath as(Table<?> alias) {
            return new ProductVariantOptionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ProductVariantOptionsRecord, Integer> getIdentity() {
        return (Identity<ProductVariantOptionsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductVariantOptionsRecord> getPrimaryKey() {
        return Keys.PRODUCT_VARIANT_OPTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<ProductVariantOptionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PRODUCT_VARIANT_OPTIONS_PRODUCT_VARIANT_ID_PRODUCT_OPTION_V_KEY);
    }

    @Override
    public List<ForeignKey<ProductVariantOptionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_VARIANT_OPTIONS__PRODUCT_VARIANT_OPTIONS_PRODUCT_VARIANT_ID_FKEY, Keys.PRODUCT_VARIANT_OPTIONS__PRODUCT_VARIANT_OPTIONS_PRODUCT_OPTION_VALUE_ID_FKEY);
    }

    private transient ProductVariantsPath _productVariants;

    /**
     * Get the implicit join path to the <code>public.product_variants</code>
     * table.
     */
    public ProductVariantsPath productVariants() {
        if (_productVariants == null)
            _productVariants = new ProductVariantsPath(this, Keys.PRODUCT_VARIANT_OPTIONS__PRODUCT_VARIANT_OPTIONS_PRODUCT_VARIANT_ID_FKEY, null);

        return _productVariants;
    }

    private transient ProductOptionValuesPath _productOptionValues;

    /**
     * Get the implicit join path to the
     * <code>public.product_option_values</code> table.
     */
    public ProductOptionValuesPath productOptionValues() {
        if (_productOptionValues == null)
            _productOptionValues = new ProductOptionValuesPath(this, Keys.PRODUCT_VARIANT_OPTIONS__PRODUCT_VARIANT_OPTIONS_PRODUCT_OPTION_VALUE_ID_FKEY, null);

        return _productOptionValues;
    }

    @Override
    public ProductVariantOptions as(String alias) {
        return new ProductVariantOptions(DSL.name(alias), this);
    }

    @Override
    public ProductVariantOptions as(Name alias) {
        return new ProductVariantOptions(alias, this);
    }

    @Override
    public ProductVariantOptions as(Table<?> alias) {
        return new ProductVariantOptions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductVariantOptions rename(String name) {
        return new ProductVariantOptions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductVariantOptions rename(Name name) {
        return new ProductVariantOptions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductVariantOptions rename(Table<?> name) {
        return new ProductVariantOptions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductVariantOptions where(Condition condition) {
        return new ProductVariantOptions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductVariantOptions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductVariantOptions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductVariantOptions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductVariantOptions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductVariantOptions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductVariantOptions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductVariantOptions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductVariantOptions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductVariantOptions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
