/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables;


import com.example.demo.jooqmodels.Keys;
import com.example.demo.jooqmodels.Public;
import com.example.demo.jooqmodels.tables.Products.ProductsPath;
import com.example.demo.jooqmodels.tables.Taxons.TaxonsPath;
import com.example.demo.jooqmodels.tables.records.ProductTaxonsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductTaxons extends TableImpl<ProductTaxonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.product_taxons</code>
     */
    public static final ProductTaxons PRODUCT_TAXONS = new ProductTaxons();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductTaxonsRecord> getRecordType() {
        return ProductTaxonsRecord.class;
    }

    /**
     * The column <code>public.product_taxons.id</code>.
     */
    public final TableField<ProductTaxonsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.product_taxons.product_id</code>.
     */
    public final TableField<ProductTaxonsRecord, Integer> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.product_taxons.taxon_id</code>.
     */
    public final TableField<ProductTaxonsRecord, Integer> TAXON_ID = createField(DSL.name("taxon_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.product_taxons.updated_at</code>.
     */
    public final TableField<ProductTaxonsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.product_taxons.created_at</code>.
     */
    public final TableField<ProductTaxonsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ProductTaxons(Name alias, Table<ProductTaxonsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProductTaxons(Name alias, Table<ProductTaxonsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.product_taxons</code> table reference
     */
    public ProductTaxons(String alias) {
        this(DSL.name(alias), PRODUCT_TAXONS);
    }

    /**
     * Create an aliased <code>public.product_taxons</code> table reference
     */
    public ProductTaxons(Name alias) {
        this(alias, PRODUCT_TAXONS);
    }

    /**
     * Create a <code>public.product_taxons</code> table reference
     */
    public ProductTaxons() {
        this(DSL.name("product_taxons"), null);
    }

    public <O extends Record> ProductTaxons(Table<O> path, ForeignKey<O, ProductTaxonsRecord> childPath, InverseForeignKey<O, ProductTaxonsRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCT_TAXONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductTaxonsPath extends ProductTaxons implements Path<ProductTaxonsRecord> {
        public <O extends Record> ProductTaxonsPath(Table<O> path, ForeignKey<O, ProductTaxonsRecord> childPath, InverseForeignKey<O, ProductTaxonsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductTaxonsPath(Name alias, Table<ProductTaxonsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductTaxonsPath as(String alias) {
            return new ProductTaxonsPath(DSL.name(alias), this);
        }

        @Override
        public ProductTaxonsPath as(Name alias) {
            return new ProductTaxonsPath(alias, this);
        }

        @Override
        public ProductTaxonsPath as(Table<?> alias) {
            return new ProductTaxonsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ProductTaxonsRecord, Integer> getIdentity() {
        return (Identity<ProductTaxonsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductTaxonsRecord> getPrimaryKey() {
        return Keys.PRODUCT_TAXONS_PKEY;
    }

    @Override
    public List<UniqueKey<ProductTaxonsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PRODUCT_TAXONS_PRODUCT_ID_TAXON_ID_KEY);
    }

    @Override
    public List<ForeignKey<ProductTaxonsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_TAXONS__PRODUCT_TAXONS_PRODUCT_ID_FKEY, Keys.PRODUCT_TAXONS__PRODUCT_TAXONS_TAXON_ID_FKEY);
    }

    private transient ProductsPath _products;

    /**
     * Get the implicit join path to the <code>public.products</code> table.
     */
    public ProductsPath products() {
        if (_products == null)
            _products = new ProductsPath(this, Keys.PRODUCT_TAXONS__PRODUCT_TAXONS_PRODUCT_ID_FKEY, null);

        return _products;
    }

    private transient TaxonsPath _taxons;

    /**
     * Get the implicit join path to the <code>public.taxons</code> table.
     */
    public TaxonsPath taxons() {
        if (_taxons == null)
            _taxons = new TaxonsPath(this, Keys.PRODUCT_TAXONS__PRODUCT_TAXONS_TAXON_ID_FKEY, null);

        return _taxons;
    }

    @Override
    public ProductTaxons as(String alias) {
        return new ProductTaxons(DSL.name(alias), this);
    }

    @Override
    public ProductTaxons as(Name alias) {
        return new ProductTaxons(alias, this);
    }

    @Override
    public ProductTaxons as(Table<?> alias) {
        return new ProductTaxons(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTaxons rename(String name) {
        return new ProductTaxons(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTaxons rename(Name name) {
        return new ProductTaxons(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductTaxons rename(Table<?> name) {
        return new ProductTaxons(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductTaxons where(Condition condition) {
        return new ProductTaxons(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductTaxons where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductTaxons where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductTaxons where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductTaxons where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductTaxons where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductTaxons where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProductTaxons where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductTaxons whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProductTaxons whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
