/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.CustomerCartSimpleItems;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerCartSimpleItemsRecord extends UpdatableRecordImpl<CustomerCartSimpleItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customer_cart_simple_items.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customer_cart_simple_items.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.customer_cart_simple_items.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customer_cart_simple_items.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.customer_cart_simple_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customer_cart_simple_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.customer_cart_simple_items.added_at</code>.
     */
    public void setAddedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customer_cart_simple_items.added_at</code>.
     */
    public LocalDateTime getAddedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerCartSimpleItemsRecord
     */
    public CustomerCartSimpleItemsRecord() {
        super(CustomerCartSimpleItems.CUSTOMER_CART_SIMPLE_ITEMS);
    }

    /**
     * Create a detached, initialised CustomerCartSimpleItemsRecord
     */
    public CustomerCartSimpleItemsRecord(Integer customerId, Integer productId, Integer quantity, LocalDateTime addedAt) {
        super(CustomerCartSimpleItems.CUSTOMER_CART_SIMPLE_ITEMS);

        setCustomerId(customerId);
        setProductId(productId);
        setQuantity(quantity);
        setAddedAt(addedAt);
        resetChangedOnNotNull();
    }
}
