/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.KnexMigrations;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KnexMigrationsRecord extends UpdatableRecordImpl<KnexMigrationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.knex_migrations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.knex_migrations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.knex_migrations.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.knex_migrations.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.knex_migrations.batch</code>.
     */
    public void setBatch(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.knex_migrations.batch</code>.
     */
    public Integer getBatch() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.knex_migrations.migration_time</code>.
     */
    public void setMigrationTime(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.knex_migrations.migration_time</code>.
     */
    public OffsetDateTime getMigrationTime() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KnexMigrationsRecord
     */
    public KnexMigrationsRecord() {
        super(KnexMigrations.KNEX_MIGRATIONS);
    }

    /**
     * Create a detached, initialised KnexMigrationsRecord
     */
    public KnexMigrationsRecord(Integer id, String name, Integer batch, OffsetDateTime migrationTime) {
        super(KnexMigrations.KNEX_MIGRATIONS);

        setId(id);
        setName(name);
        setBatch(batch);
        setMigrationTime(migrationTime);
        resetChangedOnNotNull();
    }
}
