/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.KnexMigrationsLock;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KnexMigrationsLockRecord extends UpdatableRecordImpl<KnexMigrationsLockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.knex_migrations_lock.index</code>.
     */
    public void setIndex(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.knex_migrations_lock.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.knex_migrations_lock.is_locked</code>.
     */
    public void setIsLocked(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.knex_migrations_lock.is_locked</code>.
     */
    public Integer getIsLocked() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KnexMigrationsLockRecord
     */
    public KnexMigrationsLockRecord() {
        super(KnexMigrationsLock.KNEX_MIGRATIONS_LOCK);
    }

    /**
     * Create a detached, initialised KnexMigrationsLockRecord
     */
    public KnexMigrationsLockRecord(Integer index, Integer isLocked) {
        super(KnexMigrationsLock.KNEX_MIGRATIONS_LOCK);

        setIndex(index);
        setIsLocked(isLocked);
        resetChangedOnNotNull();
    }
}
