/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.enums.OrderLineItemStatus;
import com.example.demo.jooqmodels.tables.OrderLineSimpleItems;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderLineSimpleItemsRecord extends TableRecordImpl<OrderLineSimpleItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_line_simple_items.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_line_simple_items.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.order_line_simple_items.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_line_simple_items.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.order_line_simple_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_line_simple_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.order_line_simple_items.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_line_simple_items.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>public.order_line_simple_items.order_line_item_status</code>.
     */
    public void setOrderLineItemStatus(OrderLineItemStatus value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.order_line_simple_items.order_line_item_status</code>.
     */
    public OrderLineItemStatus getOrderLineItemStatus() {
        return (OrderLineItemStatus) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderLineSimpleItemsRecord
     */
    public OrderLineSimpleItemsRecord() {
        super(OrderLineSimpleItems.ORDER_LINE_SIMPLE_ITEMS);
    }

    /**
     * Create a detached, initialised OrderLineSimpleItemsRecord
     */
    public OrderLineSimpleItemsRecord(Integer orderId, Integer productId, Integer quantity, BigDecimal unitPrice, OrderLineItemStatus orderLineItemStatus) {
        super(OrderLineSimpleItems.ORDER_LINE_SIMPLE_ITEMS);

        setOrderId(orderId);
        setProductId(productId);
        setQuantity(quantity);
        setUnitPrice(unitPrice);
        setOrderLineItemStatus(orderLineItemStatus);
        resetChangedOnNotNull();
    }
}
