/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.enums.OrderLineItemStatus;
import com.example.demo.jooqmodels.tables.OrderLineConfigurableItems;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderLineConfigurableItemsRecord extends TableRecordImpl<OrderLineConfigurableItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_line_configurable_items.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_line_configurable_items.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.order_line_configurable_items.product_variant_id</code>.
     */
    public void setProductVariantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.order_line_configurable_items.product_variant_id</code>.
     */
    public Integer getProductVariantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.order_line_configurable_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_line_configurable_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.order_line_configurable_items.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_line_configurable_items.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>public.order_line_configurable_items.order_line_item_status</code>.
     */
    public void setOrderLineItemStatus(OrderLineItemStatus value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.order_line_configurable_items.order_line_item_status</code>.
     */
    public OrderLineItemStatus getOrderLineItemStatus() {
        return (OrderLineItemStatus) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderLineConfigurableItemsRecord
     */
    public OrderLineConfigurableItemsRecord() {
        super(OrderLineConfigurableItems.ORDER_LINE_CONFIGURABLE_ITEMS);
    }

    /**
     * Create a detached, initialised OrderLineConfigurableItemsRecord
     */
    public OrderLineConfigurableItemsRecord(Integer orderId, Integer productVariantId, Integer quantity, BigDecimal unitPrice, OrderLineItemStatus orderLineItemStatus) {
        super(OrderLineConfigurableItems.ORDER_LINE_CONFIGURABLE_ITEMS);

        setOrderId(orderId);
        setProductVariantId(productVariantId);
        setQuantity(quantity);
        setUnitPrice(unitPrice);
        setOrderLineItemStatus(orderLineItemStatus);
        resetChangedOnNotNull();
    }
}
