/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.enums.OrderStatus;
import com.example.demo.jooqmodels.tables.Orders;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.orders.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.orders.shipping_fee</code>.
     */
    public void setShippingFee(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders.shipping_fee</code>.
     */
    public BigDecimal getShippingFee() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.orders.total_price</code>.
     */
    public void setTotalPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders.total_price</code>.
     */
    public BigDecimal getTotalPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.orders.order_status</code>.
     */
    public void setOrderStatus(OrderStatus value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.orders.order_status</code>.
     */
    public OrderStatus getOrderStatus() {
        return (OrderStatus) get(4);
    }

    /**
     * Setter for <code>public.orders.delivery_address</code>.
     */
    public void setDeliveryAddress(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.orders.delivery_address</code>.
     */
    public JSONB getDeliveryAddress() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.orders.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.orders.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer id, Integer customerId, BigDecimal shippingFee, BigDecimal totalPrice, OrderStatus orderStatus, JSONB deliveryAddress, LocalDateTime createdAt) {
        super(Orders.ORDERS);

        setId(id);
        setCustomerId(customerId);
        setShippingFee(shippingFee);
        setTotalPrice(totalPrice);
        setOrderStatus(orderStatus);
        setDeliveryAddress(deliveryAddress);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
