/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.ProductTaxons;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductTaxonsRecord extends UpdatableRecordImpl<ProductTaxonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product_taxons.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product_taxons.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product_taxons.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_taxons.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.product_taxons.taxon_id</code>.
     */
    public void setTaxonId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product_taxons.taxon_id</code>.
     */
    public Integer getTaxonId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.product_taxons.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.product_taxons.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.product_taxons.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.product_taxons.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductTaxonsRecord
     */
    public ProductTaxonsRecord() {
        super(ProductTaxons.PRODUCT_TAXONS);
    }

    /**
     * Create a detached, initialised ProductTaxonsRecord
     */
    public ProductTaxonsRecord(Integer id, Integer productId, Integer taxonId, LocalDateTime updatedAt, LocalDateTime createdAt) {
        super(ProductTaxons.PRODUCT_TAXONS);

        setId(id);
        setProductId(productId);
        setTaxonId(taxonId);
        setUpdatedAt(updatedAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
