/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.enums.ProductStatus;
import com.example.demo.jooqmodels.tables.ProductVariants;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductVariantsRecord extends UpdatableRecordImpl<ProductVariantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product_variants.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product_variants.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product_variants.pricing</code>.
     */
    public void setPricing(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_variants.pricing</code>.
     */
    public BigDecimal getPricing() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.product_variants.variant_name</code>.
     */
    public void setVariantName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product_variants.variant_name</code>.
     */
    public String getVariantName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.product_variants.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.product_variants.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.product_variants.position</code>.
     */
    public void setPosition(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.product_variants.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.product_variants.product_status</code>.
     */
    public void setProductStatus(ProductStatus value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.product_variants.product_status</code>.
     */
    public ProductStatus getProductStatus() {
        return (ProductStatus) get(5);
    }

    /**
     * Setter for
     * <code>public.product_variants.product_variant_image_url</code>.
     */
    public void setProductVariantImageUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.product_variants.product_variant_image_url</code>.
     */
    public String getProductVariantImageUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.product_variants.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.product_variants.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.product_variants.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.product_variants.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductVariantsRecord
     */
    public ProductVariantsRecord() {
        super(ProductVariants.PRODUCT_VARIANTS);
    }

    /**
     * Create a detached, initialised ProductVariantsRecord
     */
    public ProductVariantsRecord(Integer id, BigDecimal pricing, String variantName, Integer productId, Integer position, ProductStatus productStatus, String productVariantImageUrl, LocalDateTime updatedAt, LocalDateTime createdAt) {
        super(ProductVariants.PRODUCT_VARIANTS);

        setId(id);
        setPricing(pricing);
        setVariantName(variantName);
        setProductId(productId);
        setPosition(position);
        setProductStatus(productStatus);
        setProductVariantImageUrl(productVariantImageUrl);
        setUpdatedAt(updatedAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
