/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.ProductAssociations;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductAssociationsRecord extends UpdatableRecordImpl<ProductAssociationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.product_associations.product_association_type_id</code>.
     */
    public void setProductAssociationTypeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.product_associations.product_association_type_id</code>.
     */
    public Integer getProductAssociationTypeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product_associations.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_associations.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductAssociationsRecord
     */
    public ProductAssociationsRecord() {
        super(ProductAssociations.PRODUCT_ASSOCIATIONS);
    }

    /**
     * Create a detached, initialised ProductAssociationsRecord
     */
    public ProductAssociationsRecord(Integer productAssociationTypeId, Integer productId) {
        super(ProductAssociations.PRODUCT_ASSOCIATIONS);

        setProductAssociationTypeId(productAssociationTypeId);
        setProductId(productId);
        resetChangedOnNotNull();
    }
}
