/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.ProductConfigurableOptions;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductConfigurableOptionsRecord extends UpdatableRecordImpl<ProductConfigurableOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product_configurable_options.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product_configurable_options.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product_configurable_options.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_configurable_options.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>public.product_configurable_options.product_option_code</code>.
     */
    public void setProductOptionCode(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.product_configurable_options.product_option_code</code>.
     */
    public String getProductOptionCode() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductConfigurableOptionsRecord
     */
    public ProductConfigurableOptionsRecord() {
        super(ProductConfigurableOptions.PRODUCT_CONFIGURABLE_OPTIONS);
    }

    /**
     * Create a detached, initialised ProductConfigurableOptionsRecord
     */
    public ProductConfigurableOptionsRecord(Integer id, Integer productId, String productOptionCode) {
        super(ProductConfigurableOptions.PRODUCT_CONFIGURABLE_OPTIONS);

        setId(id);
        setProductId(productId);
        setProductOptionCode(productOptionCode);
        resetChangedOnNotNull();
    }
}
