/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.ProductOptions;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductOptionsRecord extends UpdatableRecordImpl<ProductOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product_options.code</code>.
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product_options.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.product_options.option_name</code>.
     */
    public void setOptionName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_options.option_name</code>.
     */
    public String getOptionName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.product_options.position</code>.
     */
    public void setPosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product_options.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.product_options.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.product_options.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.product_options.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.product_options.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductOptionsRecord
     */
    public ProductOptionsRecord() {
        super(ProductOptions.PRODUCT_OPTIONS);
    }

    /**
     * Create a detached, initialised ProductOptionsRecord
     */
    public ProductOptionsRecord(String code, String optionName, Integer position, LocalDateTime updatedAt, LocalDateTime createdAt) {
        super(ProductOptions.PRODUCT_OPTIONS);

        setCode(code);
        setOptionName(optionName);
        setPosition(position);
        setUpdatedAt(updatedAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
