/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooqmodels.tables.records;


import com.example.demo.jooqmodels.tables.ProductAssociationTypes;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductAssociationTypesRecord extends UpdatableRecordImpl<ProductAssociationTypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product_association_types.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product_association_types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.product_association_types.type_name</code>.
     */
    public void setTypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_association_types.type_name</code>.
     */
    public String getTypeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.product_association_types.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product_association_types.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductAssociationTypesRecord
     */
    public ProductAssociationTypesRecord() {
        super(ProductAssociationTypes.PRODUCT_ASSOCIATION_TYPES);
    }

    /**
     * Create a detached, initialised ProductAssociationTypesRecord
     */
    public ProductAssociationTypesRecord(Integer id, String typeName, LocalDateTime createdAt) {
        super(ProductAssociationTypes.PRODUCT_ASSOCIATION_TYPES);

        setId(id);
        setTypeName(typeName);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
